### PR TITLE
Updated dependencies, made path name unique.

### PR DESCRIPTION
**Pull request by mstump**
I updated the dependences, and made path names unique.  If you open more than one tap to the same CF you got error messages about the need for path names to be unique.  I asked about this error message on the cascalog google group https://groups.google.com/d/topic/cascalog-user/IfbgkXJuBhc/discussion and Nathan stated that the path must be unique, but if you're not using it, which we aren't you are free to choose a random string.  I modified the code base to use a random UUID, which solves the problem.

### CODE REVIEW

**Comment by pingles** [comment]
Thanks for the fixes!

**Comment by llasram** [comment]
Version updates are probably good -- I didn't touch anything because I didn't want to break minimum dependencies and I don't really know Maven.

I don't however think this is the right way to make different tap instances unique.  If there's a semantic clash between how the current version of Cascading treats multiple identical sinks in the same flow and the sensible resolution for Cassandra sinks, then the solution is to modify the equals() method so the taps are no longer considered equal.  Adding/swapping in a UUID just adds a layer of indirection, confusing the real problem.

pingles, if it seems sensible, I'd like to revert the UUID commit, get a test working demonstrating the issue, and then fix it by changing the semantics of equals().  mrstump, if you have time, it'd be great if you could implement the test + equals() method changes.  Otherwise, I can handle it.

**Comment by pingles** [comment]
I'm sure I've seen other taps use UUIDs for paths, in fact, I'm sure I remember seeing some bigger changes in the cascading wip to better handle these kinds of things.

I'd suggest getting on a branch, reverting the UUID commit, get some tests in and then see whether that fixes the problems that Matt was having. If that all works fine then I say we go for that?

**Comment by llasram** [comment]
Seems sensible.  I'll ping back when I have a branch with the proposed changes.

**Pull request merged**
